type SocialPlatform = 'github' | 'linkedin' | 'twitter' | 'email'

export const ICON_IDS = [
  'html',
  'css',
  'javascript',
  'typescript',
  'react',
  'tailwindcss',
  'vite',
  'nestjs',
  'laravel',
  'php',
  'python',
  'java',
  'bunjs',
  'mongodb',
  'mysql',
  'postgresql',
  'git',
  'github',
  'docker',
  'apache',
  'vim',
  'archlinux',
  'linux',
  'windows',
  'mac',
  'nuxt',
  'nuxt-content',
  'vue',
  'architecture',
  'clean-architecture',
  'components',
  'frontend',
  'open-source',
  'reading',
  'movies',
  'music',
  'coffee',
  'gaming',
] as const

export type IconId = typeof ICON_IDS[number]

export interface IconDefinition {
  icon: string
  toneClass: string
}

export const ICON_REGISTRY: Record<IconId, IconDefinition> = {
  'html': { icon: 'simple-icons:html5', toneClass: 'icon-tone-html' },
  'css': { icon: 'simple-icons:css3', toneClass: 'icon-tone-css' },
  'javascript': { icon: 'simple-icons:javascript', toneClass: 'icon-tone-javascript' },
  'typescript': { icon: 'simple-icons:typescript', toneClass: 'icon-tone-typescript' },
  'react': { icon: 'simple-icons:react', toneClass: 'icon-tone-react' },
  'tailwindcss': { icon: 'simple-icons:tailwindcss', toneClass: 'icon-tone-tailwindcss' },
  'vite': { icon: 'simple-icons:vite', toneClass: 'icon-tone-vite' },
  'nestjs': { icon: 'simple-icons:nestjs', toneClass: 'icon-tone-nestjs' },
  'laravel': { icon: 'simple-icons:laravel', toneClass: 'icon-tone-laravel' },
  'php': { icon: 'simple-icons:php', toneClass: 'icon-tone-php' },
  'python': { icon: 'simple-icons:python', toneClass: 'icon-tone-python' },
  'java': { icon: 'simple-icons:openjdk', toneClass: 'icon-tone-java' },
  'bunjs': { icon: 'simple-icons:bun', toneClass: 'icon-tone-bun' },
  'mongodb': { icon: 'simple-icons:mongodb', toneClass: 'icon-tone-mongodb' },
  'mysql': { icon: 'simple-icons:mysql', toneClass: 'icon-tone-mysql' },
  'postgresql': { icon: 'simple-icons:postgresql', toneClass: 'icon-tone-postgresql' },
  'git': { icon: 'simple-icons:git', toneClass: 'icon-tone-git' },
  'github': { icon: 'simple-icons:github', toneClass: 'icon-tone-github' },
  'docker': { icon: 'simple-icons:docker', toneClass: 'icon-tone-docker' },
  'apache': { icon: 'simple-icons:apache', toneClass: 'icon-tone-apache' },
  'vim': { icon: 'simple-icons:vim', toneClass: 'icon-tone-vim' },
  'archlinux': { icon: 'simple-icons:archlinux', toneClass: 'icon-tone-archlinux' },
  'linux': { icon: 'simple-icons:linux', toneClass: 'icon-tone-linux' },
  'windows': { icon: 'simple-icons:windows', toneClass: 'icon-tone-windows' },
  'mac': { icon: 'simple-icons:apple', toneClass: 'icon-tone-mac' },
  'nuxt': { icon: 'simple-icons:nuxt', toneClass: 'icon-tone-nuxt' },
  'nuxt-content': { icon: 'simple-icons:nuxtdotjs', toneClass: 'icon-tone-nuxt-content' },
  'vue': { icon: 'simple-icons:vuedotjs', toneClass: 'icon-tone-vue' },
  'architecture': { icon: 'mdi:sitemap', toneClass: 'icon-tone-concept' },
  'clean-architecture': { icon: 'mdi:hexagon-multiple-outline', toneClass: 'icon-tone-concept' },
  'components': { icon: 'mdi:view-grid-outline', toneClass: 'icon-tone-concept' },
  'frontend': { icon: 'mdi:monitor-dashboard', toneClass: 'icon-tone-concept' },
  'open-source': { icon: 'mdi:code-tags', toneClass: 'icon-tone-open-source' },
  'reading': { icon: 'mdi:book-open-page-variant', toneClass: 'icon-tone-reading' },
  'movies': { icon: 'mdi:movie-open', toneClass: 'icon-tone-movies' },
  'music': { icon: 'mdi:music-note', toneClass: 'icon-tone-music' },
  'coffee': { icon: 'mdi:coffee', toneClass: 'icon-tone-coffee' },
  'gaming': { icon: 'mdi:controller', toneClass: 'icon-tone-gaming' },
}

export const SOCIAL_ICON_BY_PLATFORM: Record<SocialPlatform, string> = {
  github: 'github',
  linkedin: 'linkedin',
  twitter: 'x',
  email: 'email',
}
